### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by CharlesLiuyx** [vesoft-inc/github-statistics#48]
Hi, thanks for this amazing project. 👍🏻

Is there any way to export data to CSV format.

**Comment by cliffordattractor** [comment]
Hi, I'd support this but would like to access the data that's driving the charts programatically.  

I tried to achieve this but it's designed as a SPA and there doesn't seem to be a clear API.  I'm a python dev and my js sucks but a js script that you could call, passing the desired repo name would be great. 

Thanks for building this, all the functionality is awesome.  I'd just like to be able to pull the data easily :)

**Comment by NicolaCage** [comment]
Finish
