### ISSUE TITLE
Clarify usage permission

### ISSUE THREAD

**Issue by meowcat** [vesoft-inc/github-statistics#62]
**General Question**

Maybe I'm becoming hypersensitive to this, but: It would be good if the page https://vesoft-inc.github.io/github-statistics  had a note or info about how we are allowed to use the graphs generated with the page. I would like to use screenshots in a blog post, for example.

**Comment by wey-gu** [comment]
Dear @meowcat 

Thanks for asking so, we're sorry to not claim things like how you should leverage its statistics, please feel free to use it as all public repos in our org are apache 2.0.

It'll be great if you could refer its credit if you like :).

Thanks!

NebulaGraph community.

**Comment by wey-gu** [comment]
Feel free to contribute the clarification to the repo/page

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
